import './globals.css'
import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import DefaultLayout from './components/Default'
import { Provider } from './provider'
import MainLayout from './components/MainLayout'
import variable from '@/components/Main.module.scss'

const jost = Jost({
  subsets: ['latin-ext'],
  weight: ['200', '300', '400', '500', '600', '700']
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={`${jost.className} bg-grey_10 dark:bg-paw_black`}>
          <main className='lg:flex lg:justify-between block'>
            <div className='hidden lg:block lg:w-1/2 w-0'>
              <DefaultLayout  />
            </div>
            <section className={`lg:w-1/2 w-full lg:fixed lg:left-1/2 lg:inset-y-0 flex-col flex bg-green-200`}>
              <div className={`overflow-y-auto ${variable.reset}`}>
                <MainLayout>
                  {children}
                </MainLayout>
              </div>
            </section>
          </main>
        </body>
      </Provider>
    </html>
  )
}
