import './globals.css'
import type { Metadata } from 'next'
import { Jost } from 'next/font/google'

const jost = Jost({
  subsets: ['latin-ext'],
  weight: ['200', '300', '400', '500', '600', '700']
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${jost.className} bg-[#F8F8F7]`}>{children}</body>
    </html>
  )
}
